export const publicPageChecks = [
  { route: "/", heading: /pro construction calc|calculators/i },
  { route: "/about", heading: /about/i },
  { route: "/blog", heading: /blog|field-proven|construction/i },
  { route: "/calculators", heading: /calculators/i },
  { route: "/calculators/concrete", heading: /concrete/i },
  { route: "/calculators/framing", heading: /framing/i },
  { route: "/calculators/roofing", heading: /roofing|siding/i },
  { route: "/calculators/mechanical", heading: /mechanical|site/i },
  { route: "/calculators/insulation", heading: /insulation|hvac/i },
  { route: "/calculators/finish", heading: /finish/i },
  { route: "/calculators/interior", heading: /interior/i },
  { route: "/calculators/business", heading: /business|estimating/i },
  { route: "/calculators/landscape", heading: /landscape/i },
  { route: "/calculators/outdoor", heading: /outdoor/i },
  { route: "/contact", heading: /contact/i },
  { route: "/faq", heading: /faq|frequently asked/i },
  { route: "/field-notes", heading: /field notes/i },
  { route: "/financial-terms", heading: /financial terms/i },
  { route: "/forgot-password", heading: /forgot password/i },
  { route: "/glossary", heading: /glossary/i },
  { route: "/guide", heading: /user guide/i },
  { route: "/offline", heading: /offline/i },
  { route: "/privacy", heading: /privacy/i },
  { route: "/register", heading: /sign up|register/i },
  { route: "/reset-password", heading: /reset password/i },
  { route: "/sign-in", heading: /sign in/i },
  { route: "/sign-up", heading: /sign up/i },
  { route: "/terms", heading: /terms/i },
  { route: "/unauthorized", heading: /unauthorized/i },
] as const;

export const calculatorRoutes = [
  "/calculators/business/labor-rate",
  "/calculators/business/lead-estimator",
  "/calculators/business/profit-margin",
  "/calculators/business/tax-save",
  "/calculators/concrete/block",
  "/calculators/concrete/block-wall",
  "/calculators/concrete/footing",
  "/calculators/concrete/slab",
  "/calculators/decking",
  "/calculators/finish/drywall-sheets",
  "/calculators/finish/flooring",
  "/calculators/finish/stairs",
  "/calculators/finish/trim",
  "/calculators/framing/deck-joists",
  "/calculators/framing/floor",
  "/calculators/framing/headers",
  "/calculators/framing/rafter-length",
  "/calculators/framing/rafters",
  "/calculators/framing/roof",
  "/calculators/framing/wall",
  "/calculators/framing/wall-studs",
  "/calculators/insulation/duct-sizing",
  "/calculators/insulation/drywall",
  "/calculators/insulation/r-value",
  "/calculators/insulation/r-value-tracker",
  "/calculators/interior/flooring-waste",
  "/calculators/interior/paint-gal",
  "/calculators/interior/stair-stringers",
  "/calculators/interior/trim-baseboard",
  "/calculators/landscape/gravel",
  "/calculators/landscape/mulch",
  "/calculators/landscape/sod",
  "/calculators/landscape/topsoil",
  "/calculators/management/labor",
  "/calculators/management/leads",
  "/calculators/management/margin",
  "/calculators/mechanical/btu-estimator",
  "/calculators/mechanical/ventilation-calc",
  "/calculators/outdoor/asphalt-driveway",
  "/calculators/outdoor/fence",
  "/calculators/outdoor/paver-patio",
  "/calculators/roofing/pitch",
  "/calculators/roofing/pitch-slope",
  "/calculators/roofing/shingle-bundles",
  "/calculators/roofing/shingles",
  "/calculators/roofing/siding",
  "/calculators/roofing/siding-squares",
] as const;

export const protectedSmokeRoutes = [
  { route: "/cart", heading: /cart|estimate/i },
  { route: "/saved", heading: /saved|estimates/i },
  { route: "/settings", heading: /settings|profile/i },
  { route: "/pricebook", heading: /price ?book/i },
  { route: "/command-center", heading: /command center|dashboard/i },
  { route: "/command-center/crm", heading: /crm|clients/i },
  { route: "/command-center/estimates/new", heading: /new estimate|estimate/i },
] as const;
