export const publicPageChecks = [
  { route: "/", title: /pro construction calc|contractor-grade estimating/i },
  { route: "/about", title: /about pro construction calc/i },
  { route: "/blog", title: /construction tips|guides/i },
  { route: "/blog/how-to-calculate-concrete-for-a-slab", title: /how to calculate concrete for a slab/i },
  { route: "/calculators", title: /construction calculators for contractors/i },
  { route: "/calculators/concrete", title: /concrete/i },
  { route: "/calculators/framing", title: /framing/i },
  { route: "/calculators/roofing", title: /roofing|siding/i },
  { route: "/calculators/mechanical", title: /mechanical|site/i },
  { route: "/calculators/insulation", title: /insulation|hvac/i },
  { route: "/calculators/finish", title: /finish carpentry/i },
  { route: "/calculators/interior", title: /interior/i },
  { route: "/calculators/business", title: /business|estimating/i },
  { route: "/calculators/management", title: /management/i },
  { route: "/calculators/landscape", title: /landscape/i },
  { route: "/calculators/outdoor", title: /outdoor|patios|driveways/i },
  { route: "/contact", title: /contact/i },
  { route: "/faq", title: /faq|frequently asked/i },
  { route: "/field-notes", title: /field notes/i },
  { route: "/field-notes/waste-factors-by-trade", title: /material waste factors/i },
  { route: "/financial-terms", title: /financial terms database|tax defaults/i },
  { route: "/forgot-password", title: /sign in/i, url: /\/sign-in/ },
  { route: "/glossary", title: /glossary/i },
  { route: "/guide", title: /user guide/i },
  { route: "/offline", title: /offline/i },
  { route: "/privacy", title: /privacy/i },
  { route: "/register", title: /create account|sign up/i, url: /\/sign-up/ },
  { route: "/reset-password", title: /reset password/i },
  { route: "/sign-in", title: /sign in/i },
  { route: "/sign-up", title: /create account|sign up/i },
  { route: "/terms", title: /terms/i },
  { route: "/unauthorized", title: /unauthorized/i },
] as const;

export const calculatorRoutes = [
  "/calculators/business/labor-rate",
  "/calculators/business/lead-estimator",
  "/calculators/business/profit-margin",
  "/calculators/business/tax-save",
  "/calculators/concrete/block",
  "/calculators/concrete/block-wall",
  "/calculators/concrete/footing",
  "/calculators/concrete/slab",
  "/calculators/decking",
  "/calculators/finish/drywall-sheets",
  "/calculators/finish/flooring",
  "/calculators/finish/stairs",
  "/calculators/finish/trim",
  "/calculators/framing/deck-joists",
  "/calculators/framing/floor",
  "/calculators/framing/headers",
  "/calculators/framing/rafter-length",
  "/calculators/framing/rafters",
  "/calculators/framing/roof",
  "/calculators/framing/wall",
  "/calculators/framing/wall-studs",
  "/calculators/insulation/duct-sizing",
  "/calculators/insulation/drywall",
  "/calculators/insulation/r-value",
  "/calculators/insulation/r-value-tracker",
  "/calculators/interior/flooring-waste",
  "/calculators/interior/paint-gal",
  "/calculators/interior/stair-stringers",
  "/calculators/interior/trim-baseboard",
  "/calculators/landscape/gravel",
  "/calculators/landscape/mulch",
  "/calculators/landscape/sod",
  "/calculators/landscape/topsoil",
  "/calculators/management/labor",
  "/calculators/management/leads",
  "/calculators/management/margin",
  "/calculators/mechanical/btu-estimator",
  "/calculators/mechanical/ventilation-calc",
  "/calculators/outdoor/asphalt-driveway",
  "/calculators/outdoor/fence",
  "/calculators/outdoor/paver-patio",
  "/calculators/roofing/pitch",
  "/calculators/roofing/pitch-slope",
  "/calculators/roofing/shingle-bundles",
  "/calculators/roofing/shingles",
  "/calculators/roofing/siding",
  "/calculators/roofing/siding-squares",
] as const;

export const protectedSmokeRoutes = [
  { route: "/cart", heading: /cart|estimate/i },
  { route: "/saved", heading: /saved|estimates/i },
  { route: "/settings", heading: /settings|profile/i },
  { route: "/pricebook", heading: /price ?book/i },
  { route: "/command-center", heading: /command center|dashboard|create your business/i },
  { route: "/command-center/crm", heading: /crm|clients/i },
  { route: "/command-center/estimates/new", heading: /new estimate|estimate/i },
] as const;
