import { test, expect } from "@playwright/test";
import fs from "fs";

test.describe("Office Manager — Multi-User Data Isolation", () => {
  test.skip(!process.env.TEST_USER_2_EMAIL, "Requires second test account");
  test.skip(
    !fs.existsSync("e2e/.auth/user2.json"),
    "Requires e2e/.auth/user2.json storage state",
  );

  test("User A's estimates are not visible in User B's command center", async ({
    browser,
  }) => {
    // User A session
    const ctxA = await browser.newContext({
      storageState: "e2e/.auth/user.json",
    });
    const pageA = await ctxA.newPage();

    // Create a uniquely named estimate as User A
    const uniqueTitle = `UserA-Only-${Date.now()}`;
    await pageA.goto("/cart");
    const saveBtn = pageA.getByRole("button", { name: /save estimate/i });
    if (await saveBtn.isVisible()) {
      const nameInput = pageA.getByLabel(/estimate name|title/i);
      if (await nameInput.isVisible()) await nameInput.fill(uniqueTitle);
      await saveBtn.click();
    }
    await ctxA.close();

    // User B session — log in separately
    const ctxB = await browser.newContext({
      storageState: "e2e/.auth/user2.json", // Second test account
    });
    const pageB = await ctxB.newPage();

    await pageB.goto("/command-center");
    // User B should NOT see User A's estimate
    await expect(pageB.getByText(uniqueTitle)).not.toBeVisible();
    await ctxB.close();
  });

  test("User A cannot access User B's estimate by direct URL", async ({
    browser,
  }) => {
    // This test requires knowing a saved estimate ID belonging to User B
    const estimateId = process.env.TEST_USER_2_ESTIMATE_ID;
    if (!estimateId) test.skip();

    const ctxA = await browser.newContext({
      storageState: "e2e/.auth/user.json",
    });
    const pageA = await ctxA.newPage();

    await pageA.goto(`/saved/${estimateId}`);

    // Should get 403, 404, or redirect — NOT the estimate content
    const url = pageA.url();
    const is403 = await pageA
      .getByText(/unauthorized|forbidden|not found/i)
      .isVisible();
    const isRedirected = url.includes("signin") || url.includes("unauthorized");

    expect(is403 || isRedirected).toBe(true);
    await ctxA.close();
  });

  test("share link generated by User A is accessible by User B", async ({
    browser,
  }) => {
    // Shared estimates ARE intended to cross user boundaries — verify this works
    const SHARE_CODE = process.env.TEST_SHARE_CODE;
    if (!SHARE_CODE) test.skip();

    const ctxB = await browser.newContext({
      storageState: "e2e/.auth/user2.json",
    });
    const pageB = await ctxB.newPage();

    await pageB.goto(`/sign/${SHARE_CODE}`);
    await expect(pageB.getByText(/estimate|proposal/i)).toBeVisible();
    await ctxB.close();
  });

  test("share link is accessible with NO account (public access)", async ({
    browser,
  }) => {
    const SHARE_CODE = process.env.TEST_SHARE_CODE;
    if (!SHARE_CODE) test.skip();

    const ctx = await browser.newContext({
      storageState: { cookies: [], origins: [] },
    });
    const page = await ctx.newPage();

    await page.goto(`/sign/${SHARE_CODE}`);
    await expect(page).not.toHaveURL(/signin/);
    await expect(page.getByText(/estimate|proposal/i)).toBeVisible();
    await ctx.close();
  });
});
